/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesIndexRouteImport } from './routes/states.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStatesRouteImport } from './routes/admin.states'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminLiveFeedRouteImport } from './routes/admin.live-feed'
import { Route as StatesTexasIndexRouteImport } from './routes/states.texas.index'
import { Route as StatesStateIdIndexRouteImport } from './routes/states.$stateId.index'
import { Route as StatesTexasSportsBarRouteImport } from './routes/states.texas.sports-bar'
import { Route as StatesTexasBarRouteImport } from './routes/states.texas.bar'
import { Route as StatesStateIdVenueIdRouteImport } from './routes/states.$stateId.$venueId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesIndexRoute = StatesIndexRouteImport.update({
  id: '/states/',
  path: '/states/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatesRoute = AdminStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveFeedRoute = AdminLiveFeedRouteImport.update({
  id: '/live-feed',
  path: '/live-feed',
  getParentRoute: () => AdminRoute,
} as any)
const StatesTexasIndexRoute = StatesTexasIndexRouteImport.update({
  id: '/states/texas/',
  path: '/states/texas/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateIdIndexRoute = StatesStateIdIndexRouteImport.update({
  id: '/states/$stateId/',
  path: '/states/$stateId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesTexasSportsBarRoute = StatesTexasSportsBarRouteImport.update({
  id: '/states/texas/sports-bar',
  path: '/states/texas/sports-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesTexasBarRoute = StatesTexasBarRouteImport.update({
  id: '/states/texas/bar',
  path: '/states/texas/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateIdVenueIdRoute = StatesStateIdVenueIdRouteImport.update({
  id: '/states/$stateId/$venueId',
  path: '/states/$stateId/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/live-feed': typeof AdminLiveFeedRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/states': typeof AdminStatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/states/': typeof StatesIndexRoute
  '/states/$stateId/$venueId': typeof StatesStateIdVenueIdRoute
  '/states/texas/bar': typeof StatesTexasBarRoute
  '/states/texas/sports-bar': typeof StatesTexasSportsBarRoute
  '/states/$stateId/': typeof StatesStateIdIndexRoute
  '/states/texas/': typeof StatesTexasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/live-feed': typeof AdminLiveFeedRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/states': typeof AdminStatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/states': typeof StatesIndexRoute
  '/states/$stateId/$venueId': typeof StatesStateIdVenueIdRoute
  '/states/texas/bar': typeof StatesTexasBarRoute
  '/states/texas/sports-bar': typeof StatesTexasSportsBarRoute
  '/states/$stateId': typeof StatesStateIdIndexRoute
  '/states/texas': typeof StatesTexasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/live-feed': typeof AdminLiveFeedRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/states': typeof AdminStatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/states/': typeof StatesIndexRoute
  '/states/$stateId/$venueId': typeof StatesStateIdVenueIdRoute
  '/states/texas/bar': typeof StatesTexasBarRoute
  '/states/texas/sports-bar': typeof StatesTexasSportsBarRoute
  '/states/$stateId/': typeof StatesStateIdIndexRoute
  '/states/texas/': typeof StatesTexasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explore'
    | '/forgot-password'
    | '/live'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/admin/live-feed'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/states'
    | '/admin/users'
    | '/admin/'
    | '/states/'
    | '/states/$stateId/$venueId'
    | '/states/texas/bar'
    | '/states/texas/sports-bar'
    | '/states/$stateId/'
    | '/states/texas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/live'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/admin/live-feed'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/states'
    | '/admin/users'
    | '/admin'
    | '/states'
    | '/states/$stateId/$venueId'
    | '/states/texas/bar'
    | '/states/texas/sports-bar'
    | '/states/$stateId'
    | '/states/texas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explore'
    | '/forgot-password'
    | '/live'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/admin/live-feed'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/states'
    | '/admin/users'
    | '/admin/'
    | '/states/'
    | '/states/$stateId/$venueId'
    | '/states/texas/bar'
    | '/states/texas/sports-bar'
    | '/states/$stateId/'
    | '/states/texas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StatesIndexRoute: typeof StatesIndexRoute
  StatesStateIdVenueIdRoute: typeof StatesStateIdVenueIdRoute
  StatesTexasBarRoute: typeof StatesTexasBarRoute
  StatesTexasSportsBarRoute: typeof StatesTexasSportsBarRoute
  StatesStateIdIndexRoute: typeof StatesStateIdIndexRoute
  StatesTexasIndexRoute: typeof StatesTexasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/': {
      id: '/states/'
      path: '/states'
      fullPath: '/states/'
      preLoaderRoute: typeof StatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/states': {
      id: '/admin/states'
      path: '/states'
      fullPath: '/admin/states'
      preLoaderRoute: typeof AdminStatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-feed': {
      id: '/admin/live-feed'
      path: '/live-feed'
      fullPath: '/admin/live-feed'
      preLoaderRoute: typeof AdminLiveFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/states/texas/': {
      id: '/states/texas/'
      path: '/states/texas'
      fullPath: '/states/texas/'
      preLoaderRoute: typeof StatesTexasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$stateId/': {
      id: '/states/$stateId/'
      path: '/states/$stateId'
      fullPath: '/states/$stateId/'
      preLoaderRoute: typeof StatesStateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/texas/sports-bar': {
      id: '/states/texas/sports-bar'
      path: '/states/texas/sports-bar'
      fullPath: '/states/texas/sports-bar'
      preLoaderRoute: typeof StatesTexasSportsBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/texas/bar': {
      id: '/states/texas/bar'
      path: '/states/texas/bar'
      fullPath: '/states/texas/bar'
      preLoaderRoute: typeof StatesTexasBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$stateId/$venueId': {
      id: '/states/$stateId/$venueId'
      path: '/states/$stateId/$venueId'
      fullPath: '/states/$stateId/$venueId'
      preLoaderRoute: typeof StatesStateIdVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLiveFeedRoute: typeof AdminLiveFeedRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatesRoute: typeof AdminStatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLiveFeedRoute: AdminLiveFeedRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatesRoute: AdminStatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StatesIndexRoute: StatesIndexRoute,
  StatesStateIdVenueIdRoute: StatesStateIdVenueIdRoute,
  StatesTexasBarRoute: StatesTexasBarRoute,
  StatesTexasSportsBarRoute: StatesTexasSportsBarRoute,
  StatesStateIdIndexRoute: StatesStateIdIndexRoute,
  StatesTexasIndexRoute: StatesTexasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
